version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
      - /home/fara000/root.crt:app/cert/.postgresql/root.crt
    ports:
      - 3002:3002
